theme = "onedarker"

[editor]
mouse = false
auto-format = true
continue-comments = false
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "file-name", "spinner"]
right = ["diagnostics", "position-percentage"]

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false
ignore = true

[editor.soft-wrap]
enable = true
wrap-indicator = "" # set wrap-indicator to "" to hide it

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

# my keybind taste
[keys.normal]
space.w = ":wa"
space.q = ":q!"

# thought editory.file-picker > parents = false stopped parent directories from showing, apparently not
space.f = "file_picker_in_current_directory"
space.F = "file_picker"

[keys.insert]
j.k = "normal_mode"
