#!/usr/bin/env bash
#=========================================================================#
# title       : compile rust project                                      #
# author      : sunless47                                                 #
# description : runs the long commands required to compile a rust program #
#=========================================================================#

# error handling (set -euo pipefail)
set -o errexit
set -o nounset
set -o pipefail

# rust project
PROJECT=hello_world

# opening with helix
cargo run --package $PROJECT
