#!/usr/bin/env bash
#===================================================#
# title       : configs editor                      #
# author      : sunless47                           #
# description : all user configs located in .config #
#===================================================#

# wifi
sudo killall wpa_supplicant
